### ISSUE TITLE
Using `kitchen destroy` does not delete the resource group in Azure

### ISSUE THREAD

**Issue by russellseymour** [pendrica/kitchen-azurerm#29]
I have created an Azure specific kitchen configuration file to perform integration tests.  The file is called `.kitchen.azure.yml`.  The machine was created properly when the following was run:

```
$> KITCHEN_YAML=".kitchen.azure.yml" kitchen test
```

However there was a mistake in the tests so the machine is still running.  I wanted to remove the machine and the resource group that had been created.  I thought that running the following command would do the trick:

```
$> KITCHEN_YAML=".kitchen.azure.yml" kitchen destroy
```

However it just removed it from the local list of things and not from Azure itself.

![image](https://cloud.githubusercontent.com/assets/791658/15966075/5530f590-2f19-11e6-9757-ee4c2b7d97d5.png)

**Comment by stuartpreston** [comment]
Hey Russell, what makes you think this is driver specific behaviour? What was the output when you ran kitchen destroy? Also do you have any suggestions or thoughts how to resolve? As far as I know kitchen only maintained one state file, which it must use to get the resource group name to destroy. Not sure whether the fix would be here or in TK itself...

**Comment by smurawski** [comment]
@russellseymour At least lately, it seems like resource group deletion takes quite a while.  Since this is an async action from the driver to Azure, the kitchen command returns right away but the destroy in Azure may take a while (I've seen it take 15 minutes or so).

However, once the state file (which @stuartpreston referenced) is updated, the name of the resource group is gone from kitchen's memory.

This can be a problem for just about all the cloud drivers, since it's easy to miss instances.  You add `-d always` to your `kitchen test` command and then all instances will be destroyed after a test run, regardless of pass/fail (usually a better option for CI).

**Comment by stuartpreston** [comment]
Yes the core problem is that the suite is the lifecycle container for the Azure resources, where you want it to be a composite of the configuration and the suite.

I wonder if there's a hacky workaround using a unique name for your suites like ```<% ENV['KITCHEN_YAML']-default``` but anyway I don't think there's anything specific to do in the driver so I'm going to close this for now.  Let's chat at ChefConf about it :)
